version: "3.8"
services:
  nginx:
    container_name: nginx_test_task
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    ports: 
      - "80:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./backend:/var/www/html/laravel
      - ./frontend/dist:/var/www/html/vue
    depends_on:
      - php
  
  php:
    container_name: php_test_task
    build: ./docker/php
    ports:
     - "9000:9000"
    volumes:
      - ./backend:/var/www/html/laravel
    working_dir: /var/www/html/laravel

  composer:
    container_name: composer_test_task
    image: composer/composer
    volumes:
      - ./backend:/var/www/html/laravel
    working_dir: /var/www/html/laravel
    command: install

  mysql:
    image: mysql:8.0.27
    container_name: mysql_test_task
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: raison
      MYSQL_USER: raison
      MYSQL_PASSWORD: raison
    ports:
      - "3306:3306"
